In [81]:
import json
import re
r = '[）\（\·\，\。\“ \”\?\？\」\「\…\、\《\》\；\)\(\.\(\/\)\”\“\—]'
data = []
endata = []
chdata = []

for line in open('test.txt', 'r', encoding='utf-8'):
    # val = re.sub(r,' ',line)
    data.append(json.loads(line))  
    
print('----------')

for i in range(len(data)):
    endata.append(data[i]['english'])
    chdata.append(data[i]['chinese'])

en_vocab = set(''.join(endata))
id2en = list(en_vocab)
en2id = {c:i for i,c in enumerate(id2en)}

# 分別生成中英文字典
ch_vocab = set(''.join(chdata))
id2ch = list(ch_vocab)
ch2id = {c:i for i,c in enumerate(id2ch)}

# print('英文數據:\n', endata)
# print('\n中文數據:\n', chdata)
print('\n英文字典:\n', en2id)
print('\n中文字典共計\n:', ch2id)


# en_vocab = set(''.join(endata))
# id2en = list(en_vocab)
# en2id = {c:i for i,c in enumerate(id2en)}

----------

英文字典:
 {'e': 0, 'u': 1, 'W': 2, '0': 3, '3': 4, ':': 5, "'": 6, '“': 7, '—': 8, 'x': 9, 'G': 10, 'm': 11, 'F': 12, 'K': 13, 'l': 14, 'o': 15, 'i': 16, '1': 17, 'y': 18, 'M': 19, 'z': 20, 'H': 21, '2': 22, 'd': 23, 'f': 24, 'A': 25, 'E': 26, '…': 27, 's': 28, '"': 29, 'C': 30, '(': 31, 'r': 32, ',': 33, 'L': 34, '.': 35, ')': 36, 'b': 37, 'P': 38, 'v': 39, 'c': 40, 'k': 41, 'a': 42, 'I': 43, '6': 44, 'h': 45, '-': 46, 'n': 47, 'J': 48, 'N': 49, 'B': 50, '?': 51, 'T': 52, '7': 53, ' ': 54, 't': 55, '/': 56, 'g': 57, 'p': 58, 'w': 59}

中文字典共計
: {'去': 0, '0': 1, '球': 2, '的': 3, '继': 4, '但': 5, '使': 6, '指': 7, '荐': 8, '推': 9, '为': 10, '配': 11, '将': 12, '己': 13, '杰': 14, '名': 15, '处': 16, '烈': 17, '相': 18, '亲': 19, '谓': 20, '姬': 21, '确': 22, '和': 23, '液': 24, '粒': 25, '金': 26, '活': 27, '塞': 28, '影': 29, '稀': 30, '马': 31, '录': 32, '：': 33, '前': 34, '队': 35, '喜': 36, '爱': 37, '锐': 38, '6': 39, '靠': 40, '想': 41, '大': 42, '还': 43, '所': 44, '他': 45, '往': 46, '汽': 47, '讽': 48, '主': 49,

In [82]:
en_num_data = [[en2id[en] for en in line ] for line in endata]
ch_num_data = [[ch2id[ch] for ch in line] for line in chdata]
de_num_data = [[ch2id[ch] for ch in line][1:] for line in chdata]

print('char:', endata[1])
print('index:', en_num_data[1])
# de_num_data

char: He calls the Green Book, his book of teachings, “the new gospel.
index: [21, 0, 54, 40, 42, 14, 14, 28, 54, 55, 45, 0, 54, 10, 32, 0, 0, 47, 54, 50, 15, 15, 41, 33, 54, 45, 16, 28, 54, 37, 15, 15, 41, 54, 15, 24, 54, 55, 0, 42, 40, 45, 16, 47, 57, 28, 33, 54, 7, 55, 45, 0, 54, 47, 0, 59, 54, 57, 15, 28, 58, 0, 14, 35]


In [85]:
import numpy as np

max_encoder_seq_length = max([len(txt) for txt in en_num_data])
max_decoder_seq_length = max([len(txt) for txt in ch_num_data])
print('max encoder length:', max_encoder_seq_length)
print('max decoder length:', max_decoder_seq_length)

# 將數據進行onehot處理
encoder_input_data = np.zeros((len(en_num_data), max_encoder_seq_length, len(en2id)), dtype='float32')
decoder_input_data = np.zeros((len(ch_num_data), max_decoder_seq_length, len(ch2id)), dtype='float32')
decoder_target_data = np.zeros((len(ch_num_data), max_decoder_seq_length, len(ch2id)), dtype='float32')

for i in range(len(ch_num_data)):
    for t, j in enumerate(en_num_data[i]):
        encoder_input_data[i, t, j] = 1.
    for t, j in enumerate(ch_num_data[i]):
        decoder_input_data[i, t, j] = 1.
    for t, j in enumerate(de_num_data[i]):
        decoder_target_data[i, t, j] = 1.

print('index data:\n', en_num_data[1])
print('one hot data:\n', encoder_input_data[1])

[52, 45, 0, 54, 11, 42, 55, 55, 0, 54, 42, 28, 54, 11, 42, 16, 47, 54, 40, 15, 58, 58, 0, 32, 54, 58, 45, 42, 28, 0, 54, 16, 47, 54, 55, 45, 0, 54, 40, 14, 0, 42, 47, 16, 47, 57, 35, 54, 28, 14, 42, 57, 54, 59, 42, 28, 54, 23, 0, 55, 0, 32, 46, 54, 11, 16, 47, 0, 23, 54, 37, 18, 54, 0, 14, 0, 40, 55, 32, 15, 47, 54, 58, 32, 15, 37, 0, 54, 11, 16, 40, 32, 15, 28, 40, 15, 58, 16, 40, 54, 42, 47, 42, 14, 18, 28, 16, 28, 35]
max encoder length: 165
max decoder length: 63
index data:
 [21, 0, 54, 40, 42, 14, 14, 28, 54, 55, 45, 0, 54, 10, 32, 0, 0, 47, 54, 50, 15, 15, 41, 33, 54, 45, 16, 28, 54, 37, 15, 15, 41, 54, 15, 24, 54, 55, 0, 42, 40, 45, 16, 47, 57, 28, 33, 54, 7, 55, 45, 0, 54, 47, 0, 59, 54, 57, 15, 28, 58, 0, 14, 35]
one hot data:
 [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
